### ISSUE TITLE
Means should be 0 for bigBLD events

### ISSUE THREAD

**Issue by notkevin888** [cubing/ccm#354] opened 2017-03-29 18:29 UTC
When I submitted the json for Qualifornia 2017 (which held 444bf), the mean was automatically populated with DNFs (as would happen for BLD events).  I was told by Luis that they should either be blank or 0; based on a previous json I sent in for Mental Breakdown 2016, it looks like 0 is a good option.

**Comment by jfly** [comment] 2017-03-29 18:32
I believe this is a duplicate of #323 =(

**Closed by jfly** 2017-03-29 18:32 UTC
Labels: bug
